// Writes src/features/aram/championRoles.ts: every champion's role from Data Dragon (its first
// tag), fixed in the code so every app rates a game the same way. Run again when new champions
// come out: node server/tools/champion-roles.mjs
import { writeFileSync } from 'node:fs';

const versions = await (
  await fetch('https://ddragon.leagueoflegends.com/api/versions.json')
).json();
const version = versions[0];
const { data } = await (
  await fetch(`https://ddragon.leagueoflegends.com/cdn/${version}/data/en_US/champion.json`)
).json();
const roles = Object.values(data)
  .map((c) => [Number(c.key), c.tags[0] ?? 'Fighter', c.id])
  .sort((a, b) => a[0] - b[0]);
const lines = roles.map(([key, role, id]) => `  ${key}: '${role}', // ${id}`).join('\n');
writeFileSync(
  new URL('../../src/features/aram/championRoles.ts', import.meta.url),
  `// Generated by server/tools/champion-roles.mjs from Data Dragon ${version}; do not edit by hand.
import type { Role } from './aramRating.ts';

/** Each champion's main role (Data Dragon's first tag), by champion ID. */
export const CHAMPION_ROLES: Readonly<Record<number, Role>> = {
${lines}
};
`,
);
console.log(`${roles.length} Champions aus Data Dragon ${version}`);
