// Symbols of the leaderboard's categories (Lucide), shared by the ranking, the card after a game
// and the player overview.
import {
  BarChart3,
  Coins,
  Crosshair,
  Crown,
  Flame,
  Gamepad2,
  Gauge,
  HeartPulse,
  Medal,
  PieChart,
  Shield,
  ShieldCheck,
  Skull,
  Snowflake,
  Sparkles,
  Swords,
  Target,
  TowerControl,
  TrendingUp,
  Trophy,
  Zap,
  type LucideIcon,
} from 'lucide-react';
import type { CategoryId } from './aramCategories';

export const categoryIcons: Record<CategoryId, LucideIcon> = {
  damage: Flame,
  dpm: Gauge,
  avgDpm: Gauge,
  pentas: Crown,
  ap: Sparkles,
  ad: Swords,
  kills: Skull,
  tank: Shield,
  avgDamage: BarChart3,
  wins: Trophy,
  kda: Target,
  heal: HeartPulse,
  true: Zap,
  mitigated: ShieldCheck,
  quadras: Medal,
  crit: Crosshair,
  cc: Snowflake,
  spree: TrendingUp,
  gold: Coins,
  share: PieChart,
  topDamage: Medal,
  turrets: TowerControl,
  games: Gamepad2,
};
