// Generated by server/tools/skill-orders.ts from aramkit.com (ARAM Mayhem 16.19, data of
// 2026-10-08); do not edit by hand.

export type SkillKey = 'Q' | 'W' | 'E';
/** Which ability is maxed first, second and third, e.g. 'E>Q>W'. */
export type SkillOrder = `${SkillKey}>${SkillKey}>${SkillKey}`;
/** pick: share of the champion's players who max in this order; win: their win rate (both 0-1). */
export type SkillOrderRow = { order: SkillOrder; pick: number; win: number };
export type SkillOrders = { patch: string; date: string; orders: readonly SkillOrderRow[] };

const PATCH = '16.19';
const DATE = '2026-10-08';
/** Per champion ID: the orders at least 5 % of players take, most picked first (at most 3). */
const ORDERS: Readonly<Record<number, readonly SkillOrderRow[]>> = {
  1: [
    { order: 'Q>W>E', pick: 0.59, win: 0.5 },
    { order: 'Q>E>W', pick: 0.195, win: 0.51 },
  ], // Annie
  2: [
    { order: 'Q>E>W', pick: 0.647, win: 0.477 },
    { order: 'Q>W>E', pick: 0.145, win: 0.475 },
    { order: 'E>W>Q', pick: 0.067, win: 0.478 },
  ], // Olaf
  3: [
    { order: 'Q>W>E', pick: 0.466, win: 0.514 },
    { order: 'Q>E>W', pick: 0.28, win: 0.497 },
    { order: 'W>E>Q', pick: 0.114, win: 0.542 },
  ], // Galio
  4: [
    { order: 'Q>W>E', pick: 0.85, win: 0.572 },
    { order: 'Q>E>W', pick: 0.077, win: 0.522 },
  ], // TwistedFate
  5: [
    { order: 'W>E>Q', pick: 0.486, win: 0.549 },
    { order: 'Q>E>W', pick: 0.145, win: 0.533 },
    { order: 'W>Q>E', pick: 0.116, win: 0.544 },
  ], // XinZhao
  6: [
    { order: 'W>E>Q', pick: 0.721, win: 0.479 },
    { order: 'W>Q>E', pick: 0.194, win: 0.468 },
  ], // Urgot
  7: [
    { order: 'W>Q>E', pick: 0.577, win: 0.441 },
    { order: 'Q>W>E', pick: 0.353, win: 0.449 },
    { order: 'Q>E>W', pick: 0.051, win: 0.418 },
  ], // Leblanc
  8: [
    { order: 'Q>E>W', pick: 0.781, win: 0.484 },
    { order: 'Q>W>E', pick: 0.126, win: 0.477 },
  ], // Vladimir
  9: [
    { order: 'W>Q>E', pick: 0.693, win: 0.493 },
    { order: 'W>E>Q', pick: 0.195, win: 0.492 },
  ], // Fiddlesticks
  10: [
    { order: 'E>Q>W', pick: 0.641, win: 0.562 },
    { order: 'E>W>Q', pick: 0.217, win: 0.584 },
    { order: 'Q>E>W', pick: 0.121, win: 0.554 },
  ], // Kayle
  11: [{ order: 'Q>E>W', pick: 0.951, win: 0.556 }], // MasterYi
  12: [
    { order: 'Q>W>E', pick: 0.748, win: 0.53 },
    { order: 'Q>E>W', pick: 0.136, win: 0.514 },
    { order: 'W>Q>E', pick: 0.104, win: 0.523 },
  ], // Alistar
  13: [
    { order: 'Q>E>W', pick: 0.876, win: 0.528 },
    { order: 'E>Q>W', pick: 0.093, win: 0.528 },
  ], // Ryze
  14: [
    { order: 'Q>W>E', pick: 0.706, win: 0.514 },
    { order: 'Q>E>W', pick: 0.153, win: 0.51 },
    { order: 'W>Q>E', pick: 0.114, win: 0.52 },
  ], // Sion
  15: [
    { order: 'Q>W>E', pick: 0.74, win: 0.482 },
    { order: 'W>Q>E', pick: 0.159, win: 0.486 },
    { order: 'Q>E>W', pick: 0.082, win: 0.451 },
  ], // Sivir
  16: [
    { order: 'W>Q>E', pick: 0.557, win: 0.504 },
    { order: 'W>E>Q', pick: 0.195, win: 0.5 },
    { order: 'Q>W>E', pick: 0.134, win: 0.492 },
  ], // Soraka
  17: [
    { order: 'Q>E>W', pick: 0.6, win: 0.539 },
    { order: 'E>Q>W', pick: 0.272, win: 0.545 },
    { order: 'Q>W>E', pick: 0.079, win: 0.541 },
  ], // Teemo
  18: [
    { order: 'E>Q>W', pick: 0.639, win: 0.502 },
    { order: 'Q>E>W', pick: 0.336, win: 0.499 },
  ], // Tristana
  19: [
    { order: 'Q>E>W', pick: 0.859, win: 0.479 },
    { order: 'Q>W>E', pick: 0.077, win: 0.471 },
  ], // Warwick
  20: [
    { order: 'W>Q>E', pick: 0.592, win: 0.456 },
    { order: 'Q>W>E', pick: 0.192, win: 0.473 },
    { order: 'Q>E>W', pick: 0.122, win: 0.474 },
  ], // Nunu
  21: [
    { order: 'E>Q>W', pick: 0.418, win: 0.508 },
    { order: 'E>W>Q', pick: 0.322, win: 0.526 },
    { order: 'Q>W>E', pick: 0.147, win: 0.489 },
  ], // MissFortune
  22: [
    { order: 'W>Q>E', pick: 0.649, win: 0.44 },
    { order: 'Q>W>E', pick: 0.241, win: 0.502 },
    { order: 'W>E>Q', pick: 0.091, win: 0.457 },
  ], // Ashe
  23: [
    { order: 'Q>E>W', pick: 0.668, win: 0.519 },
    { order: 'E>Q>W', pick: 0.211, win: 0.505 },
    { order: 'Q>W>E', pick: 0.072, win: 0.522 },
  ], // Tryndamere
  24: [
    { order: 'W>Q>E', pick: 0.422, win: 0.526 },
    { order: 'W>E>Q', pick: 0.256, win: 0.534 },
    { order: 'Q>W>E', pick: 0.098, win: 0.514 },
  ], // Jax
  25: [
    { order: 'W>Q>E', pick: 0.512, win: 0.559 },
    { order: 'Q>W>E', pick: 0.379, win: 0.549 },
    { order: 'W>E>Q', pick: 0.055, win: 0.565 },
  ], // Morgana
  26: [
    { order: 'Q>W>E', pick: 0.779, win: 0.528 },
    { order: 'Q>E>W', pick: 0.189, win: 0.506 },
  ], // Zilean
  27: [
    { order: 'Q>E>W', pick: 0.888, win: 0.525 },
    { order: 'Q>W>E', pick: 0.093, win: 0.525 },
  ], // Singed
  28: [
    { order: 'Q>E>W', pick: 0.809, win: 0.485 },
    { order: 'E>Q>W', pick: 0.101, win: 0.473 },
    { order: 'Q>W>E', pick: 0.063, win: 0.461 },
  ], // Evelynn
  29: [
    { order: 'E>Q>W', pick: 0.696, win: 0.503 },
    { order: 'Q>E>W', pick: 0.171, win: 0.503 },
    { order: 'E>W>Q', pick: 0.093, win: 0.441 },
  ], // Twitch
  30: [
    { order: 'Q>E>W', pick: 0.725, win: 0.476 },
    { order: 'E>Q>W', pick: 0.24, win: 0.509 },
  ], // Karthus
  31: [
    { order: 'Q>W>E', pick: 0.512, win: 0.466 },
    { order: 'Q>E>W', pick: 0.329, win: 0.481 },
    { order: 'E>Q>W', pick: 0.08, win: 0.49 },
  ], // Chogath
  32: [
    { order: 'Q>E>W', pick: 0.462, win: 0.49 },
    { order: 'E>W>Q', pick: 0.169, win: 0.507 },
    { order: 'E>Q>W', pick: 0.146, win: 0.497 },
  ], // Amumu
  33: [
    { order: 'W>E>Q', pick: 0.584, win: 0.467 },
    { order: 'W>Q>E', pick: 0.189, win: 0.459 },
    { order: 'Q>W>E', pick: 0.08, win: 0.437 },
  ], // Rammus
  34: [
    { order: 'E>Q>W', pick: 0.53, win: 0.459 },
    { order: 'Q>E>W', pick: 0.221, win: 0.457 },
    { order: 'E>W>Q', pick: 0.117, win: 0.46 },
  ], // Anivia
  35: [
    { order: 'Q>E>W', pick: 0.386, win: 0.428 },
    { order: 'W>E>Q', pick: 0.197, win: 0.559 },
    { order: 'E>Q>W', pick: 0.192, win: 0.434 },
  ], // Shaco
  36: [
    { order: 'Q>E>W', pick: 0.861, win: 0.506 },
    { order: 'Q>W>E', pick: 0.061, win: 0.483 },
    { order: 'E>Q>W', pick: 0.059, win: 0.501 },
  ], // DrMundo
  37: [
    { order: 'Q>W>E', pick: 0.415, win: 0.522 },
    { order: 'W>Q>E', pick: 0.382, win: 0.558 },
    { order: 'W>E>Q', pick: 0.146, win: 0.574 },
  ], // Sona
  38: [
    { order: 'E>Q>W', pick: 0.574, win: 0.52 },
    { order: 'E>W>Q', pick: 0.197, win: 0.53 },
    { order: 'Q>E>W', pick: 0.182, win: 0.494 },
  ], // Kassadin
  39: [
    { order: 'Q>E>W', pick: 0.761, win: 0.478 },
    { order: 'Q>W>E', pick: 0.209, win: 0.486 },
  ], // Irelia
  40: [
    { order: 'Q>E>W', pick: 0.542, win: 0.526 },
    { order: 'E>Q>W', pick: 0.212, win: 0.579 },
    { order: 'Q>W>E', pick: 0.112, win: 0.496 },
  ], // Janna
  41: [
    { order: 'Q>E>W', pick: 0.821, win: 0.517 },
    { order: 'E>Q>W', pick: 0.126, win: 0.505 },
  ], // Gangplank
  42: [
    { order: 'Q>E>W', pick: 0.599, win: 0.509 },
    { order: 'E>Q>W', pick: 0.305, win: 0.523 },
    { order: 'E>W>Q', pick: 0.076, win: 0.54 },
  ], // Corki
  43: [
    { order: 'Q>E>W', pick: 0.728, win: 0.478 },
    { order: 'E>Q>W', pick: 0.156, win: 0.546 },
    { order: 'Q>W>E', pick: 0.06, win: 0.441 },
  ], // Karma
  44: [
    { order: 'E>Q>W', pick: 0.43, win: 0.501 },
    { order: 'Q>E>W', pick: 0.36, win: 0.501 },
    { order: 'Q>W>E', pick: 0.121, win: 0.517 },
  ], // Taric
  45: [
    { order: 'Q>W>E', pick: 0.583, win: 0.508 },
    { order: 'Q>E>W', pick: 0.336, win: 0.508 },
  ], // Veigar
  48: [
    { order: 'Q>W>E', pick: 0.389, win: 0.529 },
    { order: 'E>Q>W', pick: 0.222, win: 0.499 },
    { order: 'E>W>Q', pick: 0.191, win: 0.53 },
  ], // Trundle
  50: [
    { order: 'Q>E>W', pick: 0.526, win: 0.485 },
    { order: 'Q>W>E', pick: 0.37, win: 0.478 },
    { order: 'E>Q>W', pick: 0.069, win: 0.485 },
  ], // Swain
  51: [
    { order: 'Q>W>E', pick: 0.571, win: 0.536 },
    { order: 'Q>E>W', pick: 0.348, win: 0.523 },
  ], // Caitlyn
  53: [
    { order: 'Q>E>W', pick: 0.827, win: 0.461 },
    { order: 'Q>W>E', pick: 0.117, win: 0.473 },
  ], // Blitzcrank
  55: [
    { order: 'Q>E>W', pick: 0.67, win: 0.492 },
    { order: 'E>Q>W', pick: 0.228, win: 0.522 },
    { order: 'E>W>Q', pick: 0.059, win: 0.512 },
  ], // Katarina
  56: [
    { order: 'Q>E>W', pick: 0.707, win: 0.491 },
    { order: 'Q>W>E', pick: 0.282, win: 0.504 },
  ], // Nocturne
  57: [
    { order: 'E>Q>W', pick: 0.461, win: 0.498 },
    { order: 'Q>W>E', pick: 0.208, win: 0.508 },
    { order: 'Q>E>W', pick: 0.194, win: 0.494 },
  ], // Maokai
  58: [
    { order: 'Q>E>W', pick: 0.785, win: 0.464 },
    { order: 'Q>W>E', pick: 0.18, win: 0.451 },
  ], // Renekton
  59: [
    { order: 'Q>E>W', pick: 0.882, win: 0.479 },
    { order: 'Q>W>E', pick: 0.062, win: 0.476 },
  ], // JarvanIV
  60: [
    { order: 'Q>W>E', pick: 0.558, win: 0.496 },
    { order: 'W>Q>E', pick: 0.324, win: 0.478 },
    { order: 'Q>E>W', pick: 0.078, win: 0.467 },
  ], // Elise
  61: [
    { order: 'Q>W>E', pick: 0.72, win: 0.484 },
    { order: 'W>Q>E', pick: 0.144, win: 0.487 },
    { order: 'Q>E>W', pick: 0.115, win: 0.467 },
  ], // Orianna
  62: [
    { order: 'Q>E>W', pick: 0.801, win: 0.498 },
    { order: 'E>Q>W', pick: 0.134, win: 0.5 },
  ], // MonkeyKing
  63: [
    { order: 'W>E>Q', pick: 0.508, win: 0.516 },
    { order: 'E>W>Q', pick: 0.23, win: 0.524 },
    { order: 'W>Q>E', pick: 0.142, win: 0.518 },
  ], // Brand
  64: [
    { order: 'Q>E>W', pick: 0.688, win: 0.416 },
    { order: 'Q>W>E', pick: 0.283, win: 0.441 },
  ], // LeeSin
  67: [
    { order: 'Q>W>E', pick: 0.535, win: 0.532 },
    { order: 'W>Q>E', pick: 0.425, win: 0.528 },
  ], // Vayne
  68: [
    { order: 'Q>E>W', pick: 0.792, win: 0.51 },
    { order: 'Q>W>E', pick: 0.171, win: 0.504 },
  ], // Rumble
  69: [
    { order: 'E>Q>W', pick: 0.646, win: 0.472 },
    { order: 'Q>E>W', pick: 0.195, win: 0.47 },
    { order: 'E>W>Q', pick: 0.09, win: 0.469 },
  ], // Cassiopeia
  72: [
    { order: 'Q>W>E', pick: 0.701, win: 0.49 },
    { order: 'W>Q>E', pick: 0.155, win: 0.499 },
    { order: 'Q>E>W', pick: 0.117, win: 0.468 },
  ], // Skarner
  74: [
    { order: 'Q>W>E', pick: 0.645, win: 0.513 },
    { order: 'Q>E>W', pick: 0.254, win: 0.511 },
    { order: 'W>Q>E', pick: 0.064, win: 0.506 },
  ], // Heimerdinger
  75: [
    { order: 'Q>E>W', pick: 0.453, win: 0.489 },
    { order: 'Q>W>E', pick: 0.297, win: 0.507 },
    { order: 'E>Q>W', pick: 0.131, win: 0.493 },
  ], // Nasus
  76: [
    { order: 'Q>E>W', pick: 0.874, win: 0.471 },
    { order: 'Q>W>E', pick: 0.117, win: 0.486 },
  ], // Nidalee
  78: [
    { order: 'Q>E>W', pick: 0.762, win: 0.515 },
    { order: 'Q>W>E', pick: 0.156, win: 0.51 },
  ], // Poppy
  79: [
    { order: 'Q>E>W', pick: 0.594, win: 0.495 },
    { order: 'Q>W>E', pick: 0.128, win: 0.503 },
    { order: 'E>W>Q', pick: 0.086, win: 0.491 },
  ], // Gragas
  80: [
    { order: 'Q>E>W', pick: 0.518, win: 0.498 },
    { order: 'Q>W>E', pick: 0.376, win: 0.511 },
    { order: 'W>Q>E', pick: 0.079, win: 0.517 },
  ], // Pantheon
  81: [
    { order: 'Q>E>W', pick: 0.788, win: 0.473 },
    { order: 'Q>W>E', pick: 0.174, win: 0.466 },
  ], // Ezreal
  82: [
    { order: 'Q>E>W', pick: 0.748, win: 0.474 },
    { order: 'Q>W>E', pick: 0.212, win: 0.466 },
  ], // Mordekaiser
  83: [
    { order: 'Q>E>W', pick: 0.839, win: 0.463 },
    { order: 'E>Q>W', pick: 0.088, win: 0.456 },
    { order: 'Q>W>E', pick: 0.051, win: 0.456 },
  ], // Yorick
  84: [{ order: 'Q>E>W', pick: 0.949, win: 0.444 }], // Akali
  85: [
    { order: 'Q>W>E', pick: 0.589, win: 0.459 },
    { order: 'Q>E>W', pick: 0.295, win: 0.448 },
    { order: 'W>Q>E', pick: 0.058, win: 0.463 },
  ], // Kennen
  86: [
    { order: 'E>Q>W', pick: 0.671, win: 0.467 },
    { order: 'Q>E>W', pick: 0.217, win: 0.451 },
    { order: 'E>W>Q', pick: 0.067, win: 0.466 },
  ], // Garen
  89: [
    { order: 'W>E>Q', pick: 0.371, win: 0.508 },
    { order: 'W>Q>E', pick: 0.301, win: 0.499 },
    { order: 'Q>E>W', pick: 0.155, win: 0.48 },
  ], // Leona
  90: [
    { order: 'E>Q>W', pick: 0.697, win: 0.523 },
    { order: 'E>W>Q', pick: 0.159, win: 0.526 },
    { order: 'Q>E>W', pick: 0.111, win: 0.525 },
  ], // Malzahar
  91: [
    { order: 'W>Q>E', pick: 0.741, win: 0.513 },
    { order: 'Q>W>E', pick: 0.249, win: 0.492 },
  ], // Talon
  92: [
    { order: 'Q>E>W', pick: 0.888, win: 0.485 },
    { order: 'Q>W>E', pick: 0.087, win: 0.467 },
  ], // Riven
  96: [
    { order: 'W>Q>E', pick: 0.458, win: 0.501 },
    { order: 'E>Q>W', pick: 0.23, win: 0.5 },
    { order: 'W>E>Q', pick: 0.103, win: 0.494 },
  ], // KogMaw
  98: [
    { order: 'Q>E>W', pick: 0.778, win: 0.523 },
    { order: 'E>Q>W', pick: 0.176, win: 0.528 },
  ], // Shen
  99: [
    { order: 'E>Q>W', pick: 0.666, win: 0.488 },
    { order: 'Q>E>W', pick: 0.249, win: 0.477 },
    { order: 'E>W>Q', pick: 0.061, win: 0.504 },
  ], // Lux
  101: [
    { order: 'Q>W>E', pick: 0.793, win: 0.492 },
    { order: 'Q>E>W', pick: 0.191, win: 0.473 },
  ], // Xerath
  102: [
    { order: 'E>Q>W', pick: 0.305, win: 0.534 },
    { order: 'Q>W>E', pick: 0.289, win: 0.522 },
    { order: 'E>W>Q', pick: 0.132, win: 0.547 },
  ], // Shyvana
  103: [
    { order: 'Q>W>E', pick: 0.668, win: 0.531 },
    { order: 'Q>E>W', pick: 0.298, win: 0.522 },
  ], // Ahri
  104: [{ order: 'Q>E>W', pick: 0.958, win: 0.528 }], // Graves
  105: [
    { order: 'E>W>Q', pick: 0.463, win: 0.516 },
    { order: 'E>Q>W', pick: 0.368, win: 0.503 },
    { order: 'Q>E>W', pick: 0.088, win: 0.468 },
  ], // Fizz
  106: [
    { order: 'W>Q>E', pick: 0.432, win: 0.509 },
    { order: 'Q>W>E', pick: 0.134, win: 0.501 },
    { order: 'W>E>Q', pick: 0.107, win: 0.505 },
  ], // Volibear
  107: [
    { order: 'Q>W>E', pick: 0.59, win: 0.493 },
    { order: 'Q>E>W', pick: 0.388, win: 0.511 },
  ], // Rengar
  110: [
    { order: 'Q>E>W', pick: 0.608, win: 0.467 },
    { order: 'Q>W>E', pick: 0.24, win: 0.475 },
    { order: 'W>Q>E', pick: 0.124, win: 0.474 },
  ], // Varus
  111: [
    { order: 'Q>W>E', pick: 0.374, win: 0.489 },
    { order: 'W>Q>E', pick: 0.188, win: 0.493 },
    { order: 'W>E>Q', pick: 0.123, win: 0.499 },
  ], // Nautilus
  112: [{ order: 'E>Q>W', pick: 0.941, win: 0.545 }], // Viktor
  113: [
    { order: 'W>Q>E', pick: 0.569, win: 0.497 },
    { order: 'Q>W>E', pick: 0.218, win: 0.482 },
    { order: 'Q>E>W', pick: 0.131, win: 0.479 },
  ], // Sejuani
  114: [
    { order: 'Q>E>W', pick: 0.88, win: 0.559 },
    { order: 'Q>W>E', pick: 0.116, win: 0.556 },
  ], // Fiora
  115: [{ order: 'Q>E>W', pick: 0.912, win: 0.488 }], // Ziggs
  117: [
    { order: 'E>W>Q', pick: 0.574, win: 0.529 },
    { order: 'E>Q>W', pick: 0.173, win: 0.498 },
    { order: 'Q>E>W', pick: 0.158, win: 0.437 },
  ], // Lulu
  119: [
    { order: 'Q>W>E', pick: 0.826, win: 0.513 },
    { order: 'Q>E>W', pick: 0.165, win: 0.473 },
  ], // Draven
  120: [
    { order: 'Q>W>E', pick: 0.745, win: 0.575 },
    { order: 'Q>E>W', pick: 0.238, win: 0.547 },
  ], // Hecarim
  121: [
    { order: 'W>Q>E', pick: 0.604, win: 0.493 },
    { order: 'Q>W>E', pick: 0.287, win: 0.469 },
    { order: 'Q>E>W', pick: 0.063, win: 0.45 },
  ], // Khazix
  122: [
    { order: 'Q>E>W', pick: 0.694, win: 0.489 },
    { order: 'Q>W>E', pick: 0.24, win: 0.48 },
  ], // Darius
  126: [
    { order: 'Q>E>W', pick: 0.72, win: 0.465 },
    { order: 'Q>W>E', pick: 0.257, win: 0.49 },
  ], // Jayce
  127: [
    { order: 'Q>W>E', pick: 0.785, win: 0.463 },
    { order: 'Q>E>W', pick: 0.155, win: 0.446 },
  ], // Lissandra
  131: [
    { order: 'Q>W>E', pick: 0.606, win: 0.476 },
    { order: 'Q>E>W', pick: 0.23, win: 0.459 },
    { order: 'W>Q>E', pick: 0.117, win: 0.499 },
  ], // Diana
  133: [
    { order: 'Q>E>W', pick: 0.761, win: 0.48 },
    { order: 'Q>W>E', pick: 0.074, win: 0.502 },
    { order: 'W>Q>E', pick: 0.067, win: 0.514 },
  ], // Quinn
  134: [
    { order: 'Q>E>W', pick: 0.81, win: 0.51 },
    { order: 'Q>W>E', pick: 0.153, win: 0.541 },
  ], // Syndra
  136: [
    { order: 'Q>E>W', pick: 0.828, win: 0.547 },
    { order: 'E>Q>W', pick: 0.088, win: 0.552 },
    { order: 'Q>W>E', pick: 0.081, win: 0.562 },
  ], // AurelionSol
  141: [
    { order: 'Q>W>E', pick: 0.885, win: 0.562 },
    { order: 'Q>E>W', pick: 0.074, win: 0.554 },
  ], // Kayn
  142: [{ order: 'Q>E>W', pick: 0.949, win: 0.473 }], // Zoe
  143: [
    { order: 'Q>E>W', pick: 0.6, win: 0.503 },
    { order: 'Q>W>E', pick: 0.188, win: 0.518 },
    { order: 'W>Q>E', pick: 0.075, win: 0.521 },
  ], // Zyra
  145: [
    { order: 'W>Q>E', pick: 0.507, win: 0.464 },
    { order: 'Q>E>W', pick: 0.235, win: 0.468 },
  ], // Kaisa
  147: [
    { order: 'Q>E>W', pick: 0.704, win: 0.537 },
    { order: 'E>Q>W', pick: 0.146, win: 0.533 },
    { order: 'Q>W>E', pick: 0.077, win: 0.541 },
  ], // Seraphine
  150: [
    { order: 'Q>W>E', pick: 0.69, win: 0.485 },
    { order: 'Q>E>W', pick: 0.159, win: 0.487 },
    { order: 'W>Q>E', pick: 0.126, win: 0.46 },
  ], // Gnar
  154: [
    { order: 'E>W>Q', pick: 0.592, win: 0.471 },
    { order: 'E>Q>W', pick: 0.135, win: 0.462 },
    { order: 'W>E>Q', pick: 0.107, win: 0.463 },
  ], // Zac
  157: [
    { order: 'Q>E>W', pick: 0.768, win: 0.578 },
    { order: 'E>Q>W', pick: 0.198, win: 0.614 },
  ], // Yasuo
  161: [
    { order: 'Q>W>E', pick: 0.75, win: 0.512 },
    { order: 'Q>E>W', pick: 0.212, win: 0.498 },
  ], // Velkoz
  163: [{ order: 'Q>E>W', pick: 0.924, win: 0.491 }], // Taliyah
  164: [
    { order: 'Q>E>W', pick: 0.87, win: 0.48 },
    { order: 'Q>W>E', pick: 0.087, win: 0.446 },
  ], // Camille
  166: [
    { order: 'Q>E>W', pick: 0.871, win: 0.475 },
    { order: 'E>Q>W', pick: 0.064, win: 0.478 },
    { order: 'Q>W>E', pick: 0.058, win: 0.46 },
  ], // Akshan
  200: [
    { order: 'Q>E>W', pick: 0.689, win: 0.589 },
    { order: 'E>Q>W', pick: 0.169, win: 0.592 },
  ], // Belveth
  201: [
    { order: 'Q>E>W', pick: 0.694, win: 0.472 },
    { order: 'Q>W>E', pick: 0.109, win: 0.451 },
    { order: 'E>Q>W', pick: 0.084, win: 0.468 },
  ], // Braum
  202: [
    { order: 'Q>W>E', pick: 0.787, win: 0.491 },
    { order: 'Q>E>W', pick: 0.163, win: 0.488 },
  ], // Jhin
  203: [
    { order: 'Q>W>E', pick: 0.654, win: 0.492 },
    { order: 'Q>E>W', pick: 0.311, win: 0.474 },
  ], // Kindred
  221: [
    { order: 'E>W>Q', pick: 0.529, win: 0.512 },
    { order: 'E>Q>W', pick: 0.316, win: 0.461 },
    { order: 'W>E>Q', pick: 0.092, win: 0.469 },
  ], // Zeri
  222: [
    { order: 'Q>W>E', pick: 0.784, win: 0.527 },
    { order: 'Q>E>W', pick: 0.145, win: 0.512 },
    { order: 'W>Q>E', pick: 0.062, win: 0.481 },
  ], // Jinx
  223: [
    { order: 'Q>E>W', pick: 0.504, win: 0.525 },
    { order: 'Q>W>E', pick: 0.48, win: 0.536 },
  ], // TahmKench
  233: [
    { order: 'W>Q>E', pick: 0.816, win: 0.549 },
    { order: 'W>E>Q', pick: 0.089, win: 0.56 },
    { order: 'Q>W>E', pick: 0.057, win: 0.493 },
  ], // Briar
  234: [
    { order: 'Q>E>W', pick: 0.777, win: 0.522 },
    { order: 'Q>W>E', pick: 0.198, win: 0.504 },
  ], // Viego
  235: [
    { order: 'Q>W>E', pick: 0.818, win: 0.486 },
    { order: 'Q>E>W', pick: 0.176, win: 0.478 },
  ], // Senna
  236: [{ order: 'Q>E>W', pick: 0.897, win: 0.504 }], // Lucian
  238: [
    { order: 'Q>E>W', pick: 0.879, win: 0.504 },
    { order: 'Q>W>E', pick: 0.071, win: 0.499 },
  ], // Zed
  240: [
    { order: 'Q>W>E', pick: 0.65, win: 0.497 },
    { order: 'Q>E>W', pick: 0.184, win: 0.495 },
    { order: 'W>Q>E', pick: 0.136, win: 0.491 },
  ], // Kled
  245: [
    { order: 'Q>E>W', pick: 0.924, win: 0.548 },
    { order: 'E>Q>W', pick: 0.059, win: 0.525 },
  ], // Ekko
  246: [
    { order: 'Q>W>E', pick: 0.836, win: 0.471 },
    { order: 'Q>E>W', pick: 0.148, win: 0.452 },
  ], // Qiyana
  254: [
    { order: 'Q>E>W', pick: 0.699, win: 0.472 },
    { order: 'Q>W>E', pick: 0.143, win: 0.479 },
    { order: 'E>Q>W', pick: 0.065, win: 0.467 },
  ], // Vi
  266: [{ order: 'Q>E>W', pick: 0.958, win: 0.469 }], // Aatrox
  267: [
    { order: 'W>E>Q', pick: 0.545, win: 0.526 },
    { order: 'W>Q>E', pick: 0.245, win: 0.494 },
    { order: 'Q>W>E', pick: 0.113, win: 0.459 },
  ], // Nami
  268: [
    { order: 'W>Q>E', pick: 0.695, win: 0.504 },
    { order: 'Q>W>E', pick: 0.254, win: 0.478 },
  ], // Azir
  350: [
    { order: 'Q>E>W', pick: 0.728, win: 0.566 },
    { order: 'E>W>Q', pick: 0.121, win: 0.417 },
    { order: 'E>Q>W', pick: 0.088, win: 0.433 },
  ], // Yuumi
  360: [{ order: 'Q>E>W', pick: 0.949, win: 0.489 }], // Samira
  412: [
    { order: 'Q>E>W', pick: 0.774, win: 0.446 },
    { order: 'Q>W>E', pick: 0.095, win: 0.459 },
    { order: 'E>Q>W', pick: 0.095, win: 0.436 },
  ], // Thresh
  420: [
    { order: 'E>Q>W', pick: 0.308, win: 0.488 },
    { order: 'Q>E>W', pick: 0.202, win: 0.482 },
    { order: 'E>W>Q', pick: 0.196, win: 0.495 },
  ], // Illaoi
  421: [
    { order: 'Q>E>W', pick: 0.855, win: 0.506 },
    { order: 'Q>W>E', pick: 0.079, win: 0.514 },
  ], // RekSai
  427: [
    { order: 'E>Q>W', pick: 0.65, win: 0.529 },
    { order: 'Q>E>W', pick: 0.19, win: 0.447 },
    { order: 'E>W>Q', pick: 0.122, win: 0.561 },
  ], // Ivern
  429: [
    { order: 'E>Q>W', pick: 0.774, win: 0.521 },
    { order: 'Q>E>W', pick: 0.209, win: 0.484 },
  ], // Kalista
  432: [
    { order: 'Q>W>E', pick: 0.846, win: 0.411 },
    { order: 'Q>E>W', pick: 0.076, win: 0.379 },
    { order: 'W>Q>E', pick: 0.073, win: 0.441 },
  ], // Bard
  497: [
    { order: 'W>E>Q', pick: 0.515, win: 0.486 },
    { order: 'W>Q>E', pick: 0.221, win: 0.46 },
    { order: 'Q>E>W', pick: 0.09, win: 0.458 },
  ], // Rakan
  498: [
    { order: 'E>W>Q', pick: 0.6, win: 0.51 },
    { order: 'E>Q>W', pick: 0.092, win: 0.493 },
    { order: 'W>E>Q', pick: 0.081, win: 0.499 },
  ], // Xayah
  516: [
    { order: 'Q>W>E', pick: 0.476, win: 0.494 },
    { order: 'W>Q>E', pick: 0.241, win: 0.497 },
    { order: 'Q>E>W', pick: 0.198, win: 0.484 },
  ], // Ornn
  517: [
    { order: 'W>E>Q', pick: 0.655, win: 0.5 },
    { order: 'W>Q>E', pick: 0.124, win: 0.488 },
    { order: 'Q>E>W', pick: 0.088, win: 0.48 },
  ], // Sylas
  518: [
    { order: 'Q>E>W', pick: 0.889, win: 0.461 },
    { order: 'E>Q>W', pick: 0.068, win: 0.452 },
  ], // Neeko
  526: [
    { order: 'W>E>Q', pick: 0.352, win: 0.535 },
    { order: 'Q>W>E', pick: 0.265, win: 0.529 },
    { order: 'W>Q>E', pick: 0.236, win: 0.528 },
  ], // Rell
  555: [{ order: 'Q>E>W', pick: 0.941, win: 0.472 }], // Pyke
  711: [
    { order: 'Q>W>E', pick: 0.549, win: 0.504 },
    { order: 'Q>E>W', pick: 0.424, win: 0.496 },
  ], // Vex
  777: [
    { order: 'Q>E>W', pick: 0.84, win: 0.578 },
    { order: 'Q>W>E', pick: 0.153, win: 0.552 },
  ], // Yone
  799: [
    { order: 'Q>E>W', pick: 0.844, win: 0.555 },
    { order: 'Q>W>E', pick: 0.145, win: 0.54 },
  ], // Ambessa
  800: [
    { order: 'Q>E>W', pick: 0.91, win: 0.472 },
    { order: 'E>Q>W', pick: 0.06, win: 0.469 },
  ], // Mel
  804: [
    { order: 'Q>E>W', pick: 0.744, win: 0.539 },
    { order: 'Q>W>E', pick: 0.221, win: 0.534 },
  ], // Yunara
  805: [
    { order: 'Q>E>W', pick: 0.907, win: 0.445 },
    { order: 'E>Q>W', pick: 0.052, win: 0.439 },
  ], // Locke
  875: [
    { order: 'W>Q>E', pick: 0.591, win: 0.533 },
    { order: 'Q>W>E', pick: 0.258, win: 0.52 },
    { order: 'Q>E>W', pick: 0.077, win: 0.523 },
  ], // Sett
  876: [
    { order: 'Q>E>W', pick: 0.795, win: 0.574 },
    { order: 'E>Q>W', pick: 0.147, win: 0.552 },
    { order: 'Q>W>E', pick: 0.052, win: 0.565 },
  ], // Lillia
  887: [{ order: 'Q>E>W', pick: 0.949, win: 0.583 }], // Gwen
  888: [
    { order: 'E>W>Q', pick: 0.449, win: 0.533 },
    { order: 'Q>E>W', pick: 0.217, win: 0.494 },
    { order: 'E>Q>W', pick: 0.215, win: 0.514 },
  ], // Renata
  893: [{ order: 'Q>E>W', pick: 0.96, win: 0.526 }], // Aurora
  895: [
    { order: 'Q>E>W', pick: 0.909, win: 0.518 },
    { order: 'Q>W>E', pick: 0.072, win: 0.487 },
  ], // Nilah
  897: [
    { order: 'Q>W>E', pick: 0.522, win: 0.412 },
    { order: 'Q>E>W', pick: 0.444, win: 0.422 },
  ], // KSante
  901: [
    { order: 'Q>W>E', pick: 0.747, win: 0.507 },
    { order: 'Q>E>W', pick: 0.152, win: 0.502 },
    { order: 'W>Q>E', pick: 0.095, win: 0.49 },
  ], // Smolder
  904: [
    { order: 'Q>E>W', pick: 0.888, win: 0.545 },
    { order: 'Q>W>E', pick: 0.056, win: 0.512 },
  ], // Zaahen
  910: [{ order: 'Q>E>W', pick: 0.947, win: 0.546 }], // Hwei
  950: [
    { order: 'Q>E>W', pick: 0.916, win: 0.461 },
    { order: 'Q>W>E', pick: 0.075, win: 0.454 },
  ], // Naafiri
};

/** The champion's ability max orders on aramkit.com, or undefined without data (then show none). */
export const skillOrderOf = (championId: number): SkillOrders | undefined =>
  ORDERS[championId] && { patch: PATCH, date: DATE, orders: ORDERS[championId] };
